version: "3"
services:
  web:
    build: .
    image: chrx/pnet
    ports:
      - "80:80"
    volumes:
      - ./appdc:/app/appdc
      - ./crun.py:/app/crun.py
      - ./logs:/app/logs
      - /home/nscc/th:/home/nscc/th
